server:
  port: 8001
spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      database: 1
      password: root
      host: 192.168.6.102
      port: 6379
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  rabbitmq:
    password: 123
    username: admin
    port: 5672
    host: 192.168.6.102
    publisher-confirm-type: correlated
    publisher-returns: true
    exchange: short_link_stats_exchange

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: d3ad4136556b3eba36b76f4e32eeb713
  goto-domain:
    white-list:
      enable: true
      names: '知乎,掘金,博客园,码云(Gitee), Github, 力扣;如果有需要，请联系作者：QQ2713204748, 邮箱liangyutao0905@163.com'
      details:
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - gitee.com
        - github.com
        - leetcode.cn